ALTER TABLE library
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE cover_media
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE item_library
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE games
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;