spring.application.name=game-backlog-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/game_backlog_postgres
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
